name: DartgRPC
description: gRPC demo project.
version: 0.0.1
author: Sasha Prokhorenko <djminikin@gmail.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  grpc: ^0.6.8
  protobuf: ^0.10.5
  # async: ^2.0.8

dev_dependencies:
  test: ^1.0.0
